/*
  Copyright 2018, 2019, 2020, 2021 David Healey
  This version, waistline-cli, is a fork of Waistline created by sh0gg_.

  This file is part of Waistline.

  Waistline is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  Waistline is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with app.  If not, see <http://www.gnu.org/licenses/>.
*/

// Spanish translations are written as "english == spanish" lines in i18n-es.txt (# starts a comment; {} marks the
// parts that change). This turns them into www/activities/terminal/js/terminal-i18n-es-areas.js and checks them:
// every piece of an English key must appear in the terminal's source, and {} must match on both sides.
// Usage: node tests/terminal/build-i18n.js          (writes the file; exits 1 on a mistake)
//        node tests/terminal/build-i18n.js --check   (only checks)
const fs = require("fs");
const path = require("path");

const jsDir = path.join(__dirname, "..", "..", "www", "activities", "terminal", "js");
const source = fs.readdirSync(jsDir)
  .filter(f => f.endsWith(".js") && !f.startsWith("terminal-i18n"))
  .map(f => fs.readFileSync(path.join(jsDir, f), "utf8"))
  .join("\n")
  .replace(/\\"/g, '"')
  .replace(/\\'/g, "'");

const entries = [];
const problems = [];
const seen = new Set();

fs.readFileSync(path.join(__dirname, "i18n-es.txt"), "utf8").split(/\r?\n/).forEach((raw, i) => {
  const line = raw.trim();
  if (line === "" || line.startsWith("#")) return;

  const cut = line.indexOf(" == ");
  if (cut === -1) { problems.push("line " + (i + 1) + ": no ' == '"); return; }

  // A leading ~ marks a key the code builds from several pieces, so it cannot be checked as a whole
  const composed = line.startsWith("~");
  const key = line.slice(composed ? 1 : 0, cut).trim();
  const value = line.slice(cut + 4);
  if (seen.has(key)) { problems.push("line " + (i + 1) + ": repeated key: " + key); return; }
  seen.add(key);

  const holes = (key.match(/\{\}/g) || []).length;
  const used = (value.match(/\{\d*\}/g) || []).length;
  if (used > holes) problems.push("line " + (i + 1) + ": the translation has more {} than the key: " + key);

  if (!composed) key.split("{}").map(part => part.trim()).filter(part => part.length >= 4).forEach((part) => {
    if (source.indexOf(part) === -1) problems.push("line " + (i + 1) + ": not in the source: " + JSON.stringify(part));
  });
  entries.push([key, value]);
});

if (problems.length) {
  console.log(problems.join("\n"));
  console.log(problems.length + " problem(s)");
  process.exit(1);
}

if (process.argv.includes("--check")) {
  console.log(entries.length + " translations ok");
  process.exit(0);
}

const header = fs.readFileSync(__filename, "utf8").split("*/")[0] + "*/\n";
const body = entries.map(([k, v]) => "  " + JSON.stringify(k) + ": " + JSON.stringify(v)).join(",\n");
fs.writeFileSync(path.join(jsDir, "terminal-i18n-es-areas.js"),
  header + "\n// Generated by tests/terminal/build-i18n.js from tests/terminal/i18n-es.txt. Edit that file, not this one.\napp.TerminalI18n.add(\"es\", {\n" + body + "\n});\n");
console.log(entries.length + " translations written");
