global.document = { addEventListener() {} };
global.window = { localStorage: { getItem: () => null, setItem() {} } };
global.app = {};
require("vm").runInThisContext(require("fs").readFileSync(require("path").join(__dirname, "../../www/activities/terminal/js/terminal.js"), "utf8"));
const t = app.Terminal;
let fails = 0;
const eq = (name, got, want) => { const ok = JSON.stringify(got) === JSON.stringify(want); if (!ok) fails++; console.log(ok ? "ok  " : "FAIL", name, ok ? "" : JSON.stringify(got) + " != " + JSON.stringify(want)); };
const hint = (v, cwd = []) => { t.cwd = cwd; t.el.input = { value: v }; return t.getHint(); };
const path = (s, from = []) => { const r = t.resolve(s, from); return r.error ? "ERR" : r.segments; };
const today = t.isoDate(new Date());

eq("tokenize quotes", t.tokenize('new "chicken stew" 350g'), ["new", "chicken stew", "350g"]);
eq("pwd home", t.pathToString([]), "~");
eq("pwd deep", t.pathToString(["diary", "2026-09-19"]), "~/diary/2026-09-19");
eq("cd diary", path("diary"), ["diary"]);
eq("cd ~/foods", path("~/foods", ["diary"]), ["foods"]);
eq("cd /foods", path("/foods", ["diary"]), ["foods"]);
eq("cd ..", path("..", ["diary"]), []);
eq("cd .. at root", path("..", []), []);
eq("cd ../foods", path("../foods", ["diary"]), ["foods"]);
eq("cd diary/date", path("diary/2026-09-18"), ["diary", "2026-09-18"]);
eq("cd date rel", path("2026-09-18", ["diary"]), ["diary", "2026-09-18"]);
eq("cd sibling date", path("../2026-09-17", ["diary", "2026-09-18"]), ["diary", "2026-09-17"]);
eq("cd diary/today", path("diary/today"), ["diary", today]);
eq("cd bad date", path("diary/2026-02-30"), "ERR");
eq("cd unknown", path("nope"), "ERR");
eq("cd into date child", path("x", ["diary", "2026-09-18"]), "ERR");
eq("cd case", path("DIARY"), ["diary"]);
eq("today outside diary", path("today"), "ERR");
eq("hint cmd", hint("c"), "d");
eq("hint cd arg", hint("cd di"), "ary");
eq("hint cd blank", hint("cd "), "diary");
eq("hint cd diary/", hint("cd diary/to"), "day");
eq("hint cd in diary", hint("cd y", ["diary"]), "esterday");
eq("hint cd path bad dir", hint("cd nope/x"), "");
eq("hint cd done", hint("cd diary"), "");
eq("hint help arg", hint("help cl"), "ear");
t.cwd = []; t.el = { cwd: {} };
eq("prompt", t.promptPath(), "~");
eq("valid date", t.isValidDate("2026-02-28"), true);
eq("invalid date", t.isValidDate("2026-13-01"), false);
if (fails) { console.log(fails + " failed"); process.exit(1); } else console.log("all passed");
